### PR TITLE
Add cashback api

### PR DESCRIPTION
**Pull request by daikidomon**
### All Submissions:

* [X] Have you followed the guidelines in our [Contributing](/contributing.md) document?
* [X] Have you read and signed the automated Contributor's License Agreement?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### New Feature Submissions:

1. [X] Does your submission pass tests?
2. [X] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] Have you written new tests for your core changes, as applicable?
* [X] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by daikidomon** [comment]
@shreyanshp 

> Just curious to know what does this variable do and why do we need this?

Added to make the format consistent.

**Comment by daikidomon** [comment]
@shreyanshp

I have some questions. 

- Do I need to create a new test code for cashback?
- If I create these codes, what userAuthorizationId do I use?

**Comment by shreyanshp** [comment]
@daikidomon Thanks for the PR, you can use mocks, in the same way the existing tests works, and use `xxxx` or any dummy value for tokens and user authorizations

**Comment by shreyanshp** [comment]
> CLA assistant check
Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.

> Daiki Domon seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

https://github.com/paypay/paypayopa-sdk-python/pull/52#issuecomment-754118819

@daikidomon Thanks for the PR, I can see that the commits are not linked to a github account

**Comment by daikidomon** [comment]
@shreyanshp 
Added unit test, please review.

**Comment by daikidomon** [comment]
@shreyanshp 
Added unit test, please review.

**Comment by shreyanshp** [comment]
@daikidomon Looks good!
Could you please add the docstring for the functions that would be helpful

https://app.codacy.com/gh/paypay/paypayopa-sdk-python/pullRequest?bid=21658699&prid=6748025

**Review by shreyanshp — APPROVED** [review]

**Comment by shreyanshp** [comment]
@daikidomon Thank you so much for the PR! Glad to have you here!

**Pull request merged**
